server:
  port: 8982
logging:
  file: flow.log

cxflow:
  bug-tracker: Azure
  bug-tracker-impl:
  - Azure
  branches:
  - master
  filter-severity:
  filter-category:
  - SQL_Injection
  - Stored_XSS
  - Reflected_XSS
  - Reflected_XSS_All_Clients
  - XPath_Injection
  - Second_Order_SQL_Injection
  - SOQL_SOSL_Injection
  filter-cwe:
  filter-status:
  #   - Urgent
  #   - Confirmed
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  # wiki-url: http://localhost/CxWebClient/ScanQueryDescription.aspx?queryID=430&queryVersionCode=54418097&queryTitle=SQL_Injection
  codebash-url: https://checkmarx-demo.codebashing.com/courses/

checkmarx:
  version: 9.0
  scope: access_control_api sast_rest_api
  username: <CX USERNAME>
  password: <CX PASSWORD>
  client-secret: <CHANGE ME>
  base-url: http://localhost
  multi-tenant: false
  team: /CxServer
  scan-preset: High and Medium
  url: ${checkmarx.base-url}/cxrestapi
  #WSDL Config
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
  portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
  sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl


azure:
  webhook-token: cxflow:12345
  token: <ADO or TFS TOKEN>
  url: https://dev.azure.com/
  issue-type: issue
  api-version: 5.0
  false-positive-label: false-positive
  block-merge: false
  closed-status: Done
  open-status: "To Do"
  
